### PR TITLE
StringUtils.safeFormat check for IllegalFormatException

### PR DESCRIPTION
**Pull request by drcrallen**
As mentioned in https://github.com/metamx/java-util/pull/39#discussion_r53108413

### CODE REVIEW

**Comment by gianm** [comment]
:+1: 

also- tests? Something that should pass this but fail before like `safeFormat("%d", "a string")`

**Comment by drcrallen** [comment]
@gianm added test

**Comment by gianm** [comment]
cool, still :+1:

**Comment by nishantmonu51** [comment]
:+1:

**Pull request merged**
